# Introduction

In the world, dogs are one of the most popular household pets, if not the most popular. New York City takes this popularity even further. Anecdotally, there sometimes seem to be more dogs on the street than people, and dog walking businesses are thriving. As three dog lovers living in New York, we aim to study the unique aspects of dog ownership and preference in this city. In addition, we hope to investigate the potential relationships between dogs in the city and social factors in the city such as public green space, income, and living situations. 

Specifically, we plan to explore insights about the New York City dog population and dog owners. First, we're interested in geographic and time series trends regarding various aspects of dog ownership such as the following questions: most popular dog breeds and most popular names in each zip code. Additionally, we aim to consider macro social factors and how they relate to dog ownership: are dog ownership and income level related? What about age, housing type, mental health status? Finally, our goal is to consider factors of the city and trends in dog ownership to ascertain potential aspects of living in New York City that relate to individuals owning dogs. Some of the questions we have: Do neighborhoods with more public green space lead to more dog ownership in those areas? Do dog bite rates deter dog ownership? Are ownership and family trends by borough related? Ultimately, we're curious about the specific trends in dog ownership in New York City, what social factors may relate to owning a dog, as well as the way living in New York City may affect dog ownership trends.
